# Generated by Django 4.1.3 on 2022-11-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barbers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheduling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(verbose_name="Data e hora")),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nome do cliente"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Número do cliente"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NCNF", "Not confirmed"),
                            ("CONF", "Confirmed"),
                            ("EXEC", "Executed"),
                        ],
                        default="NCNF",
                        max_length=4,
                        verbose_name="status do horário",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Horário confirmado"
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("ND", "Selecionar"),
                            ("CT", "Corte"),
                            ("BB", "Barba"),
                            ("PT", "Pintura"),
                            ("CB", "Corte e Barba"),
                            ("CP", "Corte e Pintura"),
                            ("BP", "Barba e Pintura"),
                        ],
                        default="ND",
                        max_length=2,
                        verbose_name="Tipo de trabalho",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barber",
                        to="barbers.barber",
                        verbose_name="Barbeiro",
                    ),
                ),
            ],
        ),
    ]
